name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-windows:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Package Windows Application
      uses: JackMcKew/pyinstaller-action-windows@tkinter
      with:
        path: .
        spec: partea_windows.spec

    - uses: actions/upload-artifact@v3
      with:
        name: partea-windows
        path: dist/windows

    - uses: actions/download-artifact@v3
      with:
        name: partea-windows
        path: dist/windows

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist/windows
  
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Package Linux Application
      uses: JackMcKew/pyinstaller-action-linux@tkinter
      with:
        path: .
        spec: partea_ubuntu.spec

    - uses: actions/upload-artifact@v3
      with:
        name: partea-ubuntu
        path: dist/linux
    
    - uses: actions/download-artifact@v3
      with:
        name: partea-ubuntu
        path: dist/linux

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist/linux
