name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Windows Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: partea-windows
        path: dist/windows

    - uses: actions/checkout@v2

    - name: Package Linux Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: partea-ubuntu
        path: dist/linux
        
    - name: Package MacOS Application
      uses: actions/upload-artifact@v2
      with:
        name: partea-ubuntu
        path: dist/macos
